### ISSUE TITLE
My manifesto... please read for a better future.

### ISSUE THREAD

**Issue by alltheoptions** [Nax/longflow-manifesto#14]
There is a manifesto going through over my head for a long time already... I write here to get some insight from people that are manifesting their thoughts... it's mostly about TIME because that's the only thing that matters to us, humans, I believe.

I am not an expert in programming, I am new to all of this but long enough to already see a pattern; if there's something that we need a library/framework for, there are hundreds of libraries... Is this the real future we are all hoping for? Is this the real future we all want? I know that [simplicity is complicated](https://www.youtube.com/watch?v=rFejpH_tAHM)... When I entered another "awesome-your programming language here'" repository, I've seen this:

![firefox_2018-01-19_16-55-23](https://user-images.githubusercontent.com/30186018/35159177-a0982892-fd39-11e7-8ef2-743e9dbba312.png)

So really, is this what WE all want? I really doubt so...
Most of these frameworks will die in the future, most of them really soon.
Most of them have poor docs, many of them don't have any.
I know that we can learn from the code, specially from the bad one, i know that uniqueness is very important for us, human beings. But some things should be done ONCE for ALL.
The more people are on one project, the more we can do, together.
But do you think **people want to put their time into something that can have no future**?

My idea is; before anyone wants to write a new library, each language should have their main, global "frameworks" for each big thing, for example, there should be ONE framework for:

- web framework
- GUI framework

And before we even think about writing a new one, it should be possible to:
1. Visit a website (like github.com)
2. Go into categories of each language and see what the main framework that everyone is working on.
3. Now you can implement your ideas into this framework...

I also believe we make a person/team of people to maintain this, it can be a lot of work, maybe even a full-time job.

WHAT does stop few thousand people using a framework to DONATE few $ each month and make it possible to maintain the library as a full-time job if someone wants to?

Please share your thoughts...

Regards
We can change the world!

**Comment by Nax** [comment]
I don't think this is the right place for this, sorry.
